### ISSUE TITLE
user/serviceaccount/groups impersonation fails

### ISSUE THREAD

**Issue by ppodevlabs** [projectcapsule/capsule-proxy#349] opened 2023-11-30 11:44 UTC
# Bug description

While working with flux and the multitenancy setup flux is not able to impersonate the service account which is tenant owner.

It fails with 
```timeout waiting for: [Namespace/test-hola status: 'Unknown': namespaces is forbidden: User "system:serviceaccount:test-home:gitops-reconciler" cannot list resource "namespaces" in API group "" at the cluster scope: Azure does not have opinion for this user.]```

# How to reproduce
Deploying a kind cluster and using https://github.com/ppodevlabs/capsule-gitops-testing should reproduce the issue where the `test-hola` namespace is created but the kustomization is stuck due to the above error.

# Expected behavior

the namespace should be created and the service account should be able to list namespaces.

# Logs
```
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:33.373Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:35.374Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:37.376Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:39.376Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:41.375Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:43.378Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:45.372Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:47.375Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:49.380Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
capsule-proxy-bb55f97b6-m7w4p capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:41:51.374Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
```
As you can see in the logs the groups are empty, which makes capsule not to work.

# Additional context
- Capsule-Proxy version: v0.4.6
- Helm Chart version: 0.5.1
- Kubernetes version: tested on 1.26.3 and 1.27

While checking with @maxgio92, i figured out that if i use version `clastix/capsule-proxy:v0.4.4` it works perfectly
```
capsule-proxy-59b7b6cfc8-jqblk capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:24:47.026Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":["system:serviceaccounts","system:serviceaccounts:test-home","system:authenticated"],"uri":"/apis/kustomize.toolkit.fluxcd.io/v1/namespaces/test-home/kustomizations/namespaces"}
capsule-proxy-59b7b6cfc8-jqblk capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:24:47.046Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":["system:serviceaccounts","system:serviceaccounts:test-home","system:authenticated"],"uri":"/apis/kustomize.toolkit.fluxcd.io/v1/namespaces/test-home/kustomizations/namespaces"}
capsule-proxy-59b7b6cfc8-jqblk capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T11:24:49.633Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":["system:serviceaccounts","system:serviceaccounts:test-home","system:authenticated"],"uri":"/api/v1"}
```

groups are filled in and it is able to reconcile the kustomization

**Comment by maxgio92** [comment] 2023-11-30 12:05
Hi @ppodevlabs,
thank you for time spent documenting this.

We'll work on that - actually, we should already have a patch to fix it.

@prometherion would you agree assigning this issue to me?

Thank you all

**Comment by maxgio92** [comment] 2023-11-30 20:54
I was able to reproduce the issue @ppodevlabs, by bootstrapping your simplified scenario: https://github.com/maxgio92/capsule-gitops-testing/, and [explicitly setting the version v0.4.6](https://github.com/maxgio92/capsule-gitops-testing/blob/main/capsule/capsule-proxy.yaml#L34).

Indeed, using the SA _gitops-reconciler_ `Tenant` owner, the requests to Capsule Proxy appear as below:
```
capsule-proxy-5f6968fcc4-w58bq capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T20:28:23.454Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":[],"uri":"/api/v1/namespaces"}
```

without the require Capsule group (i.e. `system:serviceaccounts:test-home`).


By testing the version built from #350, I'm able to make Flux apply the `Tenant` `Kustomization`s, because the impersonate groups now appear in the request:

```
capsule-proxy-65bcdc9c8-4xmx2 capsule-proxy {"level":"Level(-4)","ts":"2023-11-30T20:45:56.337Z","logger":"proxy","msg":"impersonating for the current request","username":"system:serviceaccount:test-home:gitops-reconciler","groups":["system:serviceaccounts","system:serviceaccounts:test-home"],"uri":"/api/v1/namespaces/test-hola"}
```

Thanks also to @prometherion for the debug done together.

**Closed** 2023-12-06 14:51 UTC
Labels: bug

**Comment by adabuleanu** [comment] 2024-02-09 15:20
Hello. I tried the image v0.5.0 and still the issue persists. 

```
{"level":"error","ts":"2024-02-09T14:01:48.606Z","msg":"Reconciliation failed after 30.767523613s, next try in 1m0s","controller":"kustomization","controllerGroup":"kustomize.toolkit.fluxcd.io","controllerKind":"Kustomization","Kustomization":{"name":"my-kustomization","namespace":"my-namespace"},"namespace":"my-namespace","name":""my-kustomization","reconcileID":"XXXXXX","revision":"XXXXXXX","error":"timeout waiting for: [Namespace/my-tenant-namespace status: 'Unknown': namespaces is forbidden: User \"system:serviceaccount:my-namespace:gitops-reconciler\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope]"}
```

When I rolled back to v0.4.5 the issue did not persist.

@oliverbaehler can you please re-open the issue?
